#!/bin/bash
# GitHub/GitLabへのリモートリポジトリ登録ガイド

echo "=== リモートリポジトリ登録手順 ==="
echo ""
echo "現在のローカルブランチ:"
git branch

echo ""
echo "--- オプション1: GitHub登録 ---"
echo "1. GitHub.com でログイン"
echo "2. 右上 '+' → New repository"
echo "3. リポジトリ名: n8n-hybrid-platform (例)"
echo "4. Private / Public 選択"
echo "5. 'Create repository' をクリック"
echo ""
echo "6. ターミナルで以下を実行:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/n8n-hybrid-platform.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "   または SSH:"
echo "   git remote add origin git@github.com:YOUR_USERNAME/n8n-hybrid-platform.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""

echo "--- オプション2: GitLab登録 ---"
echo "1. GitLab.com でログイン"
echo "2. 'New project' → 'Create blank project'"
echo "3. Project name: n8n-hybrid-platform"
echo "4. Visibility: Private / Internal / Public"
echo "5. 'Create project'"
echo ""
echo "6. ターミナルで以下を実行:"
echo "   git remote add origin https://gitlab.com/YOUR_USERNAME/n8n-hybrid-platform.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""

echo "--- オプション3: 自己ホストGit (Gitea/Gogs等) ---"
echo "1. サーバーのGit管理画面でリポジトリ作成"
echo "2. リモートURL取得 (例: https://git.example.com/user/repo.git)"
echo "3. ターミナルで:"
echo "   git remote add origin YOUR_REMOTE_URL"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""

echo "=== 共通: 認証設定 ==="
echo ""
echo "HTTPS認証 (Personal Access Token推奨):"
echo "  GitHub: Settings → Developer settings → Personal access tokens → Generate new token"
echo "  GitLab: Preferences → Access Tokens → Add new token"
echo "  scope: repo (full control)"
echo ""
echo "SSH認証:"
echo "  1. ssh-keygen -t ed25519 -C 'your_email@example.com'"
echo "  2. cat ~/.ssh/id_ed25519.pub をコピー"
echo "  3. GitHub/GitLab → Settings → SSH Keys → Add SSH key"
echo "  4. ssh -T git@github.com でテスト"
echo ""

echo "=== リモート追加後の確認 ==="
echo "  git remote -v"
echo "  git push -u origin main"
echo ""

echo "=== .env.hybrid セキュリティ再確認 ==="
echo "  cat .gitignore | grep env"
echo "  git ls-files | grep .env.hybrid  # 何も表示されなければOK"
echo ""

echo "実行準備完了。上記手順に従ってリモートを追加してください。"
