#!/bin/bash
# NPM SSL証明書取得手順ガイド

DOMAIN="ghost.100.67.3.125.sslip.io"
NPM_PORT="81"
EMAIL="your-email@example.com"  # 変更してください

echo "=========================================="
echo "  Nginx Proxy Manager SSL証明書取得手順"
echo "=========================================="
echo ""

echo "【前提確認】"
echo "1. NPM管理画面アクセス確認"
echo "   ブラウザで http://localhost:${NPM_PORT}/ または http://100.67.3.125:${NPM_PORT}/"
echo ""
echo "2. 初回ログイン情報（変更済みの場合はスキップ）"
echo "   Email: admin@example.com"
echo "   Password: changeme"
echo "   → 初回ログイン後、新しいメールアドレスとパスワード設定を要求されます"
echo ""

echo "【手順1: Proxy Host作成】"
echo "-------------------------------------------"
echo "NPM管理画面 → 左メニュー 'Hosts' → 'Proxy Hosts' → 右上 'Add Proxy Host'"
echo ""
echo "Details タブ:"
echo "  Domain Names: ${DOMAIN}"
echo "  Scheme: http"
echo "  Forward Hostname / IP: ghost"
echo "  Forward Port: 2368"
echo "  ☑ Cache Assets"
echo "  ☑ Block Common Exploits"
echo "  ☑ Websockets Support"
echo ""

echo "【手順2: SSL証明書要求】"
echo "-------------------------------------------"
echo "SSL タブに切替:"
echo "  ☑ Force SSL"
echo "  ☑ HTTP/2 Support"
echo "  ☐ HSTS Enabled (証明書取得成功後に有効化推奨)"
echo ""
echo "  SSL Certificate: 'Request a new SSL Certificate' を選択"
echo ""
echo "  Email Address for Let's Encrypt: ${EMAIL}"
echo "  ☑ Use a DNS Challenge (DNSチャレンジ使う場合。通常不要)"
echo "  ☑ I Agree to the Let's Encrypt Terms of Service"
echo ""
echo "  'Save' をクリック"
echo ""

echo "【証明書取得中...】"
echo "  数秒〜30秒程度でステータス表示"
echo "  成功: 緑チェックマーク / SSL欄に証明書表示"
echo "  失敗: 赤エラー → 下記トラブルシューティング参照"
echo ""

echo "【手順3: 動作確認】"
echo "-------------------------------------------"
echo "  ターミナルで:"
echo "    curl -I https://${DOMAIN}/"
echo ""
echo "  または:"
echo "    ./ssl-verification.sh"
echo ""
echo "  ブラウザで:"
echo "    https://${DOMAIN}/"
echo "    → 鍵マークが表示され Ghost トップページが表示されればOK"
echo ""

echo "【トラブルシューティング】"
echo "-------------------------------------------"
echo ""
echo "■ エラー: 'Challenge failed for domain'"
echo "  原因: ポート80/443が外部から到達不可"
echo "  対策:"
echo "    1. ファイアウォール確認:"
echo "       sudo ufw status"
echo "       sudo ufw allow 80/tcp"
echo "       sudo ufw allow 443/tcp"
echo ""
echo "    2. Docker compose ポート確認:"
echo "       docker ps | grep nginx-proxy-manager"
echo "       → 80:80, 443:443 が表示されること"
echo ""
echo "    3. DNS解決確認:"
echo "       nslookup ${DOMAIN}"
echo "       → 100.67.3.125 が返ること (sslip.io自動解決)"
echo ""

echo "■ エラー: 'Rate limited'"
echo "  原因: Let's Encrypt レート制限 (同一ドメイン 5回/時間)"
echo "  対策: 1時間待機してから再試行"
echo ""

echo "■ エラー: 'Invalid response from...'"
echo "  原因: Forward先が応答していない"
echo "  対策:"
echo "    1. Ghost稼働確認:"
echo "       docker ps | grep ghost"
echo "       docker logs ghost --tail 20"
echo ""
echo "    2. 内部疎通テスト:"
echo "       docker exec nginx-proxy-manager curl -I http://ghost:2368/"
echo ""

echo "■ 証明書は取得できたがブラウザで警告"
echo "  原因: Ghost側のURLがhttpのまま"
echo "  対策: 既に https に変更済み。Ghost再起動:"
echo "       docker restart ghost"
echo ""

echo "■ 301リダイレクトループ"
echo "  原因: Proxy設定とGhost URL不一致"
echo "  対策:"
echo "    1. Ghost環境変数確認:"
echo "       docker exec ghost env | grep url"
echo "       → url=https://${DOMAIN}/ であること"
echo ""
echo "    2. NPM Proxy Host 再編集:"
echo "       - Websockets Support を再確認"
echo "       - Custom Locations 未設定を確認"
echo ""

echo "【手順4: HSTS有効化 (証明書取得後)】"
echo "-------------------------------------------"
echo "  NPM → Proxy Hosts → ${DOMAIN} を編集"
echo "  SSL タブ:"
echo "    ☑ HSTS Enabled"
echo "    ☑ HSTS Subdomains (サブドメイン使う場合)"
echo "  Save"
echo ""

echo "【手順5: Security Headers追加 (推奨)】"
echo "-------------------------------------------"
echo "  詳細は SECURITY_HEADERS.md 参照"
echo "  NPM → Proxy Hosts → ${DOMAIN} → Advanced タブ"
echo "  Custom Nginx Configuration に追記"
echo ""

echo "=========================================="
echo "準備完了。NPM管理画面で上記手順を実行してください。"
echo "=========================================="
